# Generated by Django 5.1.1 on 2024-11-03 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_advisor_department_alter_instructor_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('major_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.major'),
        ),
    ]
