# Generated by Django 5.1.1 on 2024-11-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_gpa_major_student_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=5)),
                ('course_number', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.instructor')),
                ('students', models.ManyToManyField(related_name='courses', to='app.student')),
            ],
        ),
    ]
