# Generated by Django 5.1.1 on 2024-11-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='citizen',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('asian', 'Asian'), ('black', 'Black or African American'), ('hispanic', 'Hispanic or Latino'), ('native', 'Native American or Alaska Native'), ('pacific', 'Native Hawaiian or Other Pacific Islander'), ('white', 'White'), ('mixed', 'Two or More Races'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, choices=[('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior'), ('graduate', 'Graduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='app.student'),
        ),
    ]
