# Generated by Django 5.1.1 on 2024-11-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_citizen_profile_ethnicity_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('asian', 'Asian'), ('black', 'Black or African American'), ('hispanic', 'Hispanic or Latino'), ('native', 'Native American or Alaska Native'), ('pacific', 'Native Hawaiian or Other Pacific Islander'), ('caucasian', 'Caucasian'), ('mixed', 'Mixed'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20),
        ),
    ]
