# Generated by Django 5.1.1 on 2024-11-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_profile_ethnicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='available_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
