# Generated by Django 5.1.1 on 2024-11-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_course_available_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
    ]
